---
# this should be removed once systemd's ".mount succeeded" spam during healthcheck stops
- name: add syslog blacklist
  template:
    dest: /etc/rsyslog.d/01-blacklist.conf
    src: templates/01-blacklist.conf.j2
  notify: restart rsyslog
- name: setup journald
  template:
    dest: /etc/systemd/journald.conf
    src: templates/journald.conf.j2
  notify: restart journald
