---
- name: download crictl
  get_url:
    url: https://github.com/kubernetes-sigs/cri-tools/releases/download/v1.18.0/crictl-v1.18.0-linux-amd64.tar.gz
    checksum: sha256:876dd2b3d0d1c2590371f940fb1bf1fbd5f15aebfbe456703ee465d959700f4a
    dest: /var/cache/crictl.tar.gz

- name: unpack crictl
  unarchive:
    remote_src: yes
    src: /var/cache/crictl.tar.gz
    dest: /usr/local/bin

- name: get crictl completion
  shell: "/usr/local/bin/crictl completion"
  changed_when: false
  register: crictl_completion

- name: install crictl completion
  copy:
    dest: /usr/share/bash-completion/completions/crictl
    content: "{{ crictl_completion.stdout }}"
