---
- name: template MetalLB config
  template:
    src: templates/metallb-config.yaml.j2
    dest: /tmp/kube-manifests/metallb/config.yaml

- name: apply MetalLB manifest
  command: kubectl apply -k /tmp/kube-manifests/metallb

- name: check if MetalLB memberlist secret exists
  command: kubectl get secret memberlist -n metallb-system
  register: metallb_secret_exists
  changed_when: false
  failed_when: metallb_secret_exists.rc != 0 and metallb_secret_exists.rc != 1

- name: create MetalLB memberlist secret
  shell: kubectl create secret generic -n metallb-system memberlist --from-literal=secretkey="$(openssl rand -base64 128)"
  when: metallb_secret_exists.rc == 1

- name: template IP floater config
  template:
    src: templates/floater-config.yaml.j2
    dest: /tmp/kube-manifests/hcloud-ip-floater/secret.yaml

- name: apply hcloud-metallb-floater manifest
  command: kubectl apply -k /tmp/kube-manifests/hcloud-ip-floater
