---
- name: copy hcloud secret manifest
  template:
    src: templates/hcloud-secret.yml.j2
    dest: /var/lib/rancher/k3s/server/manifests/hcloud-secret.yaml

- name: copy hcloud cloud controller manifest
  template:
    src: templates/hcloud-ccm.yml.j2
    dest: /var/lib/rancher/k3s/server/manifests/hcloud-ccm.yaml

- name: copy hcloud csi manifest
  template:
    src: templates/hcloud-csi.yml.j2
    dest: /var/lib/rancher/k3s/server/manifests/hcloud-csi.yaml
