---
- hosts: all
  roles:
  - defaults
  - setup
  - cri

- hosts: master
  roles:
  - defaults
  - master
  - cni

- hosts: worker
  roles:
  - defaults
  - worker

- hosts: master
  roles:
  - defaults
  - addons
